apiVersion: batch/v1
kind: Job
metadata:
  name: integrationtest
  labels:
    role: integrationtest
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        role: integrationtest
    spec:
      containers:
      - image: postman/newman:alpine
        ### UPDATE COLLECTION ON NEXT LINE
        args: ["run", "https://www.getpostman.com/collections/08a31b94a3b9fd831861","--environment","/usr/src/app/global_postman_vars.json","--insecure", "--ignore-redirects"]
        imagePullPolicy: "IfNotPresent"
        name: integrationtest
        volumeMounts:
        - mountPath: /usr/src/app/global_postman_vars.json
          name: ${RELEASE}-global-env-vars-postman
          subPath: global_postman_vars.json
      restartPolicy: Never
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: global_postman_vars.json
            path: global_postman_vars.json
          name: ${RELEASE}-global-env-vars-postman
        name: ${RELEASE}-global-env-vars-postman