# global:
  # envs:
    # need this because it's part of config, but not
    # PD_DELEGATOR_HTTPS_PUBLIC_PORT: "443"
    
# #############################################################
# # pingfederate-admin values.
# #############################################################
# pingfederate-admin:
#   enabled: true
#   # container:
#   #   waitFor:
#   #     pingdirectory:
#   #       service: ldaps
#   image:
#     repository: pingidentity
#     name: pingfederate
#     tag: 10.2.0-edge
#     pullPolicy: Always
pingfederate-admin:
  enabled: true
  envs:
    PF_CONSOLE_AUTHENTICATION: NATIVE
    SERVER_PROFILE_BASE_PATH: profiles/pingfederate
    SERVER_PROFILE_BASE_URL: https://github.com/PandikKumar/citadel
    SERVER_PROFILE_PARENT: BASE
    SERVER_PROFILE_PATH: profiles/pingfederate_admin
    SERVER_PROFILE_URL: https://github.com/PandikKumar/citadel

# #############################################################
# # pingfederate-engine values
# #############################################################
pingfederate-engine:
#   enabled: true
#   image:
#     repository: pingidentity
#     name: pingfederate
#     tag: 10.2.0-edge
#     pullPolicy: Always
#   clustering:
#     autoscaling:
#       enabled: false
  enabled: true
  envs:
    PF_CONSOLE_AUTHENTICATION: NATIVE
    SERVER_PROFILE_PATH: profiles/pingfederate
    SERVER_PROFILE_URL: https://github.com/PandikKumar/citadel
  container:
    replicaCount: 1