{{- include "pinglib.configmap" (list . "global") -}}

{{- define "global.configmap" -}}
{{- $top := index . 0 -}}
{{- $v := index . 1 -}}
data:
  {{ include "global.private.host.port" (list $top $v "PF_ENGINE" "pingfederate-engine") }}
  {{ include "global.private.host.port" (list $top $v "PF_ADMIN" "pingfederate-admin") }}

  {{ include "global.public.host.port" (list $top $v "PF_ENGINE" "pingfederate-engine") }}
  {{ include "global.public.host.port" (list $top $v "PF_ADMIN" "pingfederate-admin") }}
{{- end -}}
