{{- include "pinglib.configmap" (list . "global") -}}

{{- define "global.configmap" -}}
{{- $top := index . 0 -}}
{{- $v := index . 1 -}}
data:
  {{ include "global.private.host.port" (list $top $v "PA_ADMIN" "pingaccess-admin") }}
  {{ include "global.private.host.port" (list $top $v "PA_ENGINE" "pingaccess-engine") }}
  {{ include "global.private.host.port" (list $top $v "PD_CONSOLE" "pingdataconsole") }}
  {{ include "global.private.host.port" (list $top $v "PDS_ENGINE" "pingdatasync") }}
  {{ include "global.private.host.port" (list $top $v "PDG_ENGINE" "pingdatagovernance") }}
  {{ include "global.private.host.port" (list $top $v "PDGP_ENGINE" "pingdatagovernancepap") }}
  {{ include "global.private.host.port" (list $top $v "PD_DELEGATOR" "pingdelegator") }}
  {{ include "global.private.host.port" (list $top $v "PD_ENGINE" "pingdirectory") }}
  {{ include "global.private.host.port" (list $top $v "PDP_ENGINE" "pingdirectoryproxy") }}
  {{ include "global.private.host.port" (list $top $v "PF_ENGINE" "pingfederate-engine") }}
  {{ include "global.private.host.port" (list $top $v "PF_ADMIN" "pingfederate-admin") }}

  {{ include "global.public.host.port" (list $top $v "PA_ADMIN" "pingaccess-admin") }}
  {{ include "global.public.host.port" (list $top $v "PA_ENGINE" "pingaccess-engine") }}
  {{ include "global.public.host.port" (list $top $v "PD_CONSOLE" "pingdataconsole") }}
  {{ include "global.public.host.port" (list $top $v "PDS_ENGINE" "pingdatasync") }}
  {{ include "global.public.host.port" (list $top $v "PDG_ENGINE" "pingdatagovernance") }}
  {{ include "global.public.host.port" (list $top $v "PDGP_ENGINE" "pingdatagovernancepap") }}
  {{ include "global.public.host.port" (list $top $v "PD_DELEGATOR" "pingdelegator") }}
  {{ include "global.public.host.port" (list $top $v "PD_ENGINE" "pingdirectory") }}
  {{ include "global.public.host.port" (list $top $v "PDP_ENGINE" "pingdirectoryproxy") }}
  {{ include "global.public.host.port" (list $top $v "PF_ENGINE" "pingfederate-engine") }}
  {{ include "global.public.host.port" (list $top $v "PF_ADMIN" "pingfederate-admin") }}
{{- end -}}
